### ISSUE TITLE
could `showln` or a variant return the value of the expression instead of `nothing`?

### ISSUE THREAD

**Issue by tpapp** [timholy/DebuggingUtilities.jl#3]
This would be useful in the following situation: suppose I am debugging

``` julia
foo(complicated, arguments, bar(x))
```

then I could wrap part of this in the macro as

``` julia
foo(complicated, arguments, @showln(bar(x)))
```

If I understand correctly, the current implementation requires

``` julia
tmp = bar(x)
@showln tmp
foo(complicated, arguments, tmp)
```

instead.

**Comment by timholy** [comment]
Closed by 5f20ac4347f10687595cabaa2b304d073f7cf836.
